const { EmbedBuilder } = require('discord.js');
const db = require('../utils/db');
// 確保 event.js 存在，否則這行會報錯
// const { getActiveEvents } = require('./event'); 

module.exports = {
    name: 'combine',
        aliases: ['c', '合成', 'upgrade'],
            execute: async (message, args) => { // 直接用傳進來的 args
                    // 因為 index.js 傳進來的是去掉指令名的 args，所以長度檢查改為 3
                            if (!args || args.length < 3) {
                                        const embed = new EmbedBuilder()
                                                        .setTitle('❌ 格式錯誤')
                                                                        .setDescription('請輸入 `~c [序號1] [序號2] [序號3]`\n例如：`~c 0 1 2`')
                                                                                        .setColor(0xFF0000);
                                                                                                    return message.reply({ embeds: [embed] });
                                                                                                            }

                                                                                                                    const userId = message.author.id;
                                                                                                                            let data = db.read();
                                                                                                                                    const player = data.players?.[userId];

                                                                                                                                            if (!player || !player.inventory || player.inventory.length < 3) {
                                                                                                                                                        return message.reply('❌ 背包物品不足 3 個，無法合成。');
                                                                                                                                                                }

                                                                                                                                                                        // 轉為數字並檢查範圍
                                                                                                                                                                                const idxs = args.slice(0, 3).map(x => parseInt(x));
                                                                                                                                                                                        const [i1, i2, i3] = idxs;

                                                                                                                                                                                                // 檢查：是否為數字、是否重複、是否超出範圍
                                                                                                                                                                                                        if (idxs.some(isNaN) || 
                                                                                                                                                                                                                    new Set(idxs).size !== 3 || 
                                                                                                                                                                                                                                idxs.some(i => i < 0 || i >= player.inventory.length)) {
                                                                                                                                                                                                                                            return message.reply('❌ 序號無效、重複或超出了背包範圍！');
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                            const item1 = player.inventory[i1];
                                                                                                                                                                                                                                                                    const item2 = player.inventory[i2];
                                                                                                                                                                                                                                                                            const item3 = player.inventory[i3];

                                                                                                                                                                                                                                                                                    if (item1.name !== item2.name || item1.name !== item3.name) {
                                                                                                                                                                                                                                                                                                return message.reply('❌ 必須選擇 3 個**同名**物品！');
                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                // 執行合成
                                                                                                                                                                                                                                                                                                                        const newItem = {
                                                                                                                                                                                                                                                                                                                                    name: `✨ ${item1.name}`,
                                                                                                                                                                                                                                                                                                                                                origin: item1.origin || '未知',
                                                                                                                                                                                                                                                                                                                                                            rarity: 'rare'
                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                            // 倒序刪除 (核心邏輯正確，保留)
                                                                                                                                                                                                                                                                                                                                                                                    const sortedIdx = [...idxs].sort((a, b) => b - a);
                                                                                                                                                                                                                                                                                                                                                                                            sortedIdx.forEach(idx => player.inventory.splice(idx, 1));

                                                                                                                                                                                                                                                                                                                                                                                                    player.inventory.push(newItem);
                                                                                                                                                                                                                                                                                                                                                                                                            player.weekly_points = (player.weekly_points || 0) + 50;

                                                                                                                                                                                                                                                                                                                                                                                                                    db.write(data);

                                                                                                                                                                                                                                                                                                                                                                                                                            const res = new EmbedBuilder()
                                                                                                                                                                                                                                                                                                                                                                                                                                        .setTitle('✨ 合成成功！')
                                                                                                                                                                                                                                                                                                                                                                                                                                                    .setDescription(`3 個 **${item1.name}** 已進化為 **${newItem.name}**`)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                .setColor(0x00FFFF);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message.reply({ embeds: [res] });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };