const db = require('../utils/db');

module.exports = {
    name: 'interactionCreate',
        async execute(interaction) {
                // 只處理按鈕
                        if (!interaction.isButton()) return;

                                // 處理購買邏輯 (buy_1, buy_2...)
                                        if (interaction.customId.startsWith('buy_')) {
                                                    const itemId = parseInt(interaction.customId.split('_')[1]);
                                                                const userId = interaction.user.id;
                                                                            let data = db.read();
                                                                                        
                                                                                                    const player = data.players[userId];
                                                                                                                if (!player) return interaction.reply({ content: '❌ 請先開始遊戲！', ephemeral: true });

                                                                                                                            // 商店物品清單 (建議以後也抽出來放 utils/shopItems.js)
                                                                                                                                        const shopItems = {
                                                                                                                                                        1: { name: '維修工具', cost: 50 },
                                                                                                                                                                        2: { name: '穩定劑', cost: 100 },
                                                                                                                                                                                        3: { name: '背包擴展', cost: 150 },
                                                                                                                                                                                                        4: { name: '稀有配方', cost: 200 },
                                                                                                                                                                                                                        5: { name: '傳說碎片', cost: 300 },
                                                                                                                                                                                                                                        6: { name: '恢復藥劑', cost: 75 },
                                                                                                                                                                                                                                                        7: { name: '感知增幅', cost: 120 },
                                                                                                                                                                                                                                                                        8: { name: '加速器', cost: 250 }
                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                const item = shopItems[itemId];
                                                                                                                                                                                                                                                                                                            const crystals = player.entropy_crystal || 0;

                                                                                                                                                                                                                                                                                                                        // 1. 檢查錢夠不夠
                                                                                                                                                                                                                                                                                                                                    if (crystals < item.cost) {
                                                                                                                                                                                                                                                                                                                                                    return interaction.reply({ 
                                                                                                                                                                                                                                                                                                                                                                        content: `❌ 你的熵結晶不足！需要 ${item.cost}，你只有 ${crystals}。`, 
                                                                                                                                                                                                                                                                                                                                                                                            ephemeral: true 
                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                    // 2. 扣錢
                                                                                                                                                                                                                                                                                                                                                                                                                                                player.entropy_crystal = crystals - item.cost;

                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 3. 給予獎勵 (這裡示範增加到背包，如果是「擴展背包」要改寫別的邏輯)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!player.inventory) player.inventory = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    player.inventory.push({ name: item.name, rarity: 'shop' });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 4. 存檔
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            db.write(data);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await interaction.reply({ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        content: `✅ 購買成功！獲得了 **${item.name}**，剩餘 💎 ${player.entropy_crystal}。`, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ephemeral: true 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };